project:
  type: website
  output-dir: docs
  resources: images/*
  render:
    - "scripts/accessStormEventsData.qmd"
    - "scripts/analyseStormEventsData.qmd"
    - "scripts/powerSimulations.qmd"
    - "index.qmd"

website:
  title: "EcoTRACE"
  navbar:
    left:
      - text: Preprocessing Storm Events
        menu:
        - href: scripts/accessStormEventsData.qmd
          text: Access & Tidy Data
        - href: scripts/analyseStormEventsData.qmd
          text: Analyse Data
      - href: scripts/powerSimulations.qmd
        text: Power Analyses

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

