project:
  type: website
  output-dir: docs
  resources: images/*
  render:
    - "scripts/accessStormEventsData.qmd"
    - "scripts/analyseStormEventsData.qmd"
    - "scripts/powerSimulations.qmd"
    - "scripts/supplementaryInformation.qmd"
    - "index.qmd"

website:
  title: "EcoTRACE"
  navbar:
    left:
      - text: Extreme Weather Events Data
        menu:
        - href: scripts/accessStormEventsData.qmd
          text: Access & Preprocessing
        - href: scripts/analyseStormEventsData.qmd
          text: Analysis
      - href: scripts/powerSimulations.qmd
        text: Power Analyses
      - href: scripts/supplementaryInformation.qmd
        text: Supplementary Information
  page-footer: 'Site maintained by [emmanuel.guizarrosales@unibe.ch](mailto:emmanuel.guizarrosales@unibe.ch?subject=EcoTRACE%20Registered%20Report)'

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

